package com.gestioneEventi.models;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents an activity within an event.
 * Activities can be predefined or custom, and are associated with specific events.
 * Each activity belongs to an event and has a creator.
 *
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Activity {

    /**
     * Unique identifier for the activity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name or title of the activity.
     */
    private String name;

    /**
     * Detailed description of the activity.
     */
    private String description;

    /**
     * Indicates whether this is a custom activity or a predefined one.
     * Custom activities are created by users, while predefined ones are system-defined.
     */
    private boolean isCustom;

    /**
     * The event that this activity belongs to.
     * Many-to-one relationship with Event entity.
     * Cannot be null - every activity must belong to an event.
     */
    @ManyToOne(optional = false)
    private Event event;

    /**
     * User who created this activity.
     * Many-to-one relationship with User entity.
     * Cannot be null - every activity must have a creator.
     */
    @ManyToOne(optional = false)
    private User createdBy;

    /**
     * Custom equals implementation based on ID.
     * Required for proper entity comparison in collections.
     *
     * @param o Object to compare with
     * @return true if objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof Activity))
            return false;
        Activity other = (Activity) o;
        return id != null && id.equals(other.getId());
    }

    /**
     * Custom hashCode implementation.
     * Uses class hashCode for consistency with equals.
     *
     * @return hash code value
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}