package com.gestioneEventi.models;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents an event in the event management system.
 * Events can be of different types (events, activities, team building) and can have
 * multiple activities, invited users, and participants.
 *
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Event {

    /**
     * Unique identifier for the event.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title or name of the event.
     */
    private String title;

    /**
     * Start date of the event.
     * Represents the beginning of the event period.
     */
    private LocalDate startDate;

    /**
     * End date of the event.
     * Represents the end of the event period.
     */
    private LocalDate endDate;

    /**
     * Type of the event.
     * Determines the category and behavior of the event.
     * Uses string enumeration for database storage.
     */
    @Enumerated(EnumType.STRING)
    private EventType eventType;

    /**
     * User who created this event.
     * Many-to-one relationship with User entity.
     */
    @ManyToOne
    private User createdBy;

    /**
     * Users who are invited to this event.
     * Many-to-many relationship with User entity.
     * Ignored in JSON serialization to prevent circular references.
     */
    @ManyToMany
    @JsonIgnore
    @JoinTable(name = "event_users",
        joinColumns = @JoinColumn(name = "event_id"),
        inverseJoinColumns = @JoinColumn(name = "user_id"))
    private Set<User> invitedUsers = new HashSet<>();

    /**
     * Activities associated with this event.
     * One-to-many relationship with Activity entity.
     * All operations cascade to activities, and orphan removal is enabled.
     */
    @OneToMany(mappedBy = "event", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Activity> activities = new HashSet<>();

    /**
     * Custom equals implementation based on ID.
     * Required for proper entity comparison in collections.
     *
     * @param o Object to compare with
     * @return true if objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof Event))
            return false;
        Event other = (Event) o;
        return id != null && id.equals(other.getId());
    }

    /**
     * Custom hashCode implementation.
     * Uses class hashCode for consistency with equals.
     *
     * @return hash code value
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}