package com.gestioneEventi.models;

import java.time.LocalDate;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a vacation or leave request in the system.
 * Tracks employee time off requests with approval status and date ranges.
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Ferie {

    /**
     * Unique identifier for the vacation request.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title or description of the vacation request.
     */
    private String title;

    /**
     * Start date of the vacation period.
     */
    private LocalDate startDate;

    /**
     * End date of the vacation period.
     */
    private LocalDate endDate;

    /**
     * Current status of the vacation request.
     * Indicates whether it's pending, approved, or rejected.
     */
    private Status status;

    /**
     * Associated event if the vacation is event-related.
     * Many-to-one relationship with Event entity.
     * Can be null for standalone vacation requests.
     */
    @ManyToOne
    private Event event;

    /**
     * User who created this vacation request.
     * Many-to-one relationship with User entity.
     */
    @ManyToOne
    private User createdBy;
}