package com.gestioneEventi.models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a user's participation in an event.
 * Tracks the participation status and links users to events they are participating in.
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Schema(description = "Modello di partecipazione di un utente a un evento")
public class Partecipation {

    /**
     * Unique identifier for the participation record.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "ID univoco della partecipazione", example = "1")
    private Long id;

    /**
     * Current status of the participation.
     * Indicates whether the user has accepted, rejected, or is still considering the invitation.
     */
    @Schema(
        description = "Stato della partecipazione (PENDING = in sospeso, ACCEPTED = accettato, REJECTED = rifiutato)",
        example = "PENDING",
        allowableValues = {"PENDING", "ACCEPTED", "REJECTED"}
    )
    private PartecipationStatus status;

    /**
     * The event that the user is participating in.
     * Many-to-one relationship with Event entity.
     */
    @ManyToOne
    @Schema(description = "Evento associato alla partecipazione")
    private Event event;

    /**
     * The user who is participating in the event.
     * Many-to-one relationship with User entity.
     */
    @ManyToOne
    @Schema(description = "Utente partecipante")
    private User user;
}