package com.gestioneEventi.models;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Represents a user's participation in a team building event.
 * Tracks specific details for team building activities including chosen activities and date ranges.
 *
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TeamBuildingPartecipation {

    /**
     * Unique identifier for the team building participation.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user participating in the team building event.
     * Many-to-one relationship with User entity.
     * Cannot be null - every participation must have a user.
     */
    @ManyToOne(optional = false)
    private User user;

    /**
     * The team building event being participated in.
     * Many-to-one relationship with Event entity.
     * Cannot be null - every participation must belong to an event.
     */
    @ManyToOne(optional = false)
    private Event event;

    /**
     * ID of the specific activity chosen by the user within the team building event.
     * References an Activity entity.
     */
    private Long chosenActivityId;

    /**
     * Start date for this specific participation.
     * May differ from the event's overall dates.
     */
    private LocalDate startDate;

    /**
     * End date for this specific participation.
     * May differ from the event's overall dates.
     */
    private LocalDate endDate;

    /**
     * Custom equals implementation based on ID.
     * Required for proper entity comparison in collections.
     *
     * @param o Object to compare with
     * @return true if objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof TeamBuildingPartecipation))
            return false;
        TeamBuildingPartecipation other = (TeamBuildingPartecipation) o;
        return id != null && id.equals(other.getId());
    }

    /**
     * Custom hashCode implementation.
     * Uses class hashCode for consistency with equals.
     *
     * @return hash code value
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}