package com.gestioneEventi.models;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Represents a user in the event management system.
 * Users can authenticate, participate in events, and belong to user groups.
 * Each user has a role that determines their permissions in the system.
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString(exclude = "groups")
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's email address.
     * Must be unique and is used for authentication.
     * Cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * User's display name.
     * Optional field for user identification.
     */
    private String name;

    /**
     * User's role in the system.
     * Determines permissions and access levels.
     * Uses string enumeration for database storage.
     */
    @Enumerated(EnumType.STRING)
    private Role role;

    /**
     * Groups that this user belongs to.
     * Many-to-many relationship with UserGroup.
     * Uses eager fetching for immediate access to group information.
     * Note: EAGER fetch is temporary - may be changed to LAZY if performance issues occur.
     */
    @ManyToMany(fetch = FetchType.EAGER) // EAGER temporaneo, se il server crasha ancora alla creazione di un evento si fixa il service
    @JoinTable(name = "user_group_membership",
        joinColumns = @JoinColumn(name = "user_id"),
        inverseJoinColumns = @JoinColumn(name = "group_id"))
    private Set<UserGroup> groups = new HashSet<>();
}