package com.gestioneEventi.models;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Represents a group of users in the system.
 * User groups are used to organize users for better management and access control.
 * Groups can contain multiple users and users can belong to multiple groups.
 *
 */
@Data
@EqualsAndHashCode(exclude = "members")
@Entity
public class UserGroup {

    /**
     * Unique identifier for the user group.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the user group.
     * Used to identify and describe the group.
     */
    private String name;

    /**
     * Users who are members of this group.
     * Many-to-many relationship with User entity.
     * The relationship is mapped by the "groups" field in the User entity.
     * Ignored in JSON serialization to prevent circular references.
     */
    @JsonIgnore
    @ManyToMany(mappedBy = "groups")
    private Set<User> members = new HashSet<>();
}