spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourdb
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 480
  frontend:
    url: http://localhost:5173
  employee-directory:
    url: http://localhost:8081
    fallback-allow-if-unreachable: true