spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestione_eventi?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  # Configurazione errori personalizzati
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  employee-directory:
    url: http://localhost:8081
    fallback-allow-if-unreachable: true
    cache-ttl-minutes: 10
    cache-max-size: 10000