spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestione_eventi?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 60
  employee-directory:
    url: http://localhost:8081   # esempio, backend fittizio per EmployeeDirectoryClient
    fallback-allow-if-unreachable: true
